import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar/Navbar";
// import Modal from "./components/modals/Modal";
import LoginModal from "./components/modals/LoginModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DjangoBNB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content = (
    <div>
      <p>This is the content of the modal.</p>
    </div>
  );
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar />
        <div className="pt-26">{children}</div>
        <LoginModal />
        {/* Uncomment the line below to test the Modal component */}
        {/* <Modal label="Modal Title" content={content} isOpen={true} /> */}
      </body>
    </html>
  );
}
